apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: resources
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
