apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
      configMapRef:
        name: devops-config